# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f5c41d8f57db3e6b46d80f880eb9467204104390dd8fdcdc813a16959c1c5f520eb8cf004ec30abffaa9fc1910335c9fceeeafbf1bfc4d443eb9a8b8b7970c4

test:
  secret_key_base: add5a914404b4c464cdede1cc08cca884cb378ab09bf7d663c272b88f2bfce2efdcf9cc663941e8772f510655552de6ed422408374ed1880b8d32ad47d2d7e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
